### ISSUE TITLE
Collapsing sidebar has problem with left sidebar

### ISSUE THREAD

**Issue by baseband5** [kmaasrud/clean-theme-obsidian#1]
Code provided cannot unfold already folded left sidebar. Below option to use it only with right sidebar

`.app-container.is-right-sidedock-collapsed .side-dock.mod-right:not(:hover) {
  width: 0px !important;
}`

**Comment by kmaasrud** [comment]
The autohiding sidebars have been improved in the current version, and this shouldn't be a problem anymore. Please reopen if the issue persists.
